### ISSUE TITLE
push failure

### ISSUE THREAD

**Issue by fabricetiennette** [transifex/transifex-swift-cli#17]
Hello!

Just got this XLIFF parsing error while trying to push via txios-cli 

![Screenshot 2022-01-05 at 22 28 31](https://user-images.githubusercontent.com/19342638/148292045-b4b6c0d7-3458-4239-a2ef-51484a9050f8.png)

Am using Transifex Native SDK (iOS)
Xcode 13.1

Hope someone can help me

**Comment by fabricetiennette** [comment]
> got and error while trying to push via txios-cli ![Screenshot 2022-01-05 at 16 09 55](https://user-images.githubusercontent.com/19342638/148241111-c11af176-3bb0-45e9-99ad-b5826aa7c0cd.png)
> 
> Hope someone can help me

just figure it out but now am facing this XLIFF parsing error
![Screenshot 2022-01-05 at 17 25 26](https://user-images.githubusercontent.com/19342638/148252684-5a529940-0ed6-41a7-8c5d-60fec1de17db.png)

**Comment by fabricetiennette** [comment]
just figure it out but now am facing this XLIFF parsing error
![Screenshot 2022-01-05 at 17 25 26](https://user-images.githubusercontent.com/19342638/148252898-cdd581bc-2ead-4eaa-90b4-83997034c27d.png)

**Comment by stelabouras** [comment]
Hello Fabrice! Sorry for the late reply.

In order to discover more information about the XLIFF parsing failure, you can use the `--verbose` flag when pushing.

e.g.

```
txios-cli push --token "YOUR_TOKEN" --secret "YOUR_SECRET" --project YourProject.xcodeproj --verbose
```

If you still cannot figure out where is the parsing failure and if the XLIFF file does not include any sensitive informaton, you can pass the `--keep-temp-folder` that will not remove the temporary folder and then upload the XLIFF file here so we can investigate the issue further.
